In [1]:
import pandas as pd

In [2]:
submission = pd.read_csv("submission (8).csv")

In [3]:
submission

            ID                                             Target
0    ID_QNYPTX  Bandeko awa na misu na ngai nazomona obele ban...
1    ID_CLCVQW  Biloko nazomona awa namoni eza obele mama moko...
2    ID_INJFRV  Ishangu mbiri dzemativi ose emakumbo. Dzine ru...
3    ID_XKFXQJ  Motuka esali mikolo ebele ezali akufa liboso y...
4    ID_TYVXWN  Miti midiki yakati rebeyi ine matanda matete n...
..         ...                                                ...
887  ID_CUDWBK  Munhukadzi akachena. Akapfeka hembe ine ruvara...
888  ID_ARVDNP  Photo elakisi biso mwa loboko esimbi mwa kisi ...
889  ID_EROPVG  Miti yemijakaranda mihombe ine tirangi yakakur...
890  ID_VYRCXO  Awa eza esika bakonzi batelemelaka makambo ya ...
891  ID_HYKQPA  Chimushini chakatsvetwa pasi paivhu Chine ruva...

[892 rows x 2 columns]

In [5]:
submission_lowercased = submission.copy()
submission_lowercased['Target'] = submission_lowercased['Target'].str.lower()
submission_lowercased

            ID                                             Target
0    ID_QNYPTX  bandeko awa na misu na ngai nazomona obele ban...
1    ID_CLCVQW  biloko nazomona awa namoni eza obele mama moko...
2    ID_INJFRV  ishangu mbiri dzemativi ose emakumbo. dzine ru...
3    ID_XKFXQJ  motuka esali mikolo ebele ezali akufa liboso y...
4    ID_TYVXWN  miti midiki yakati rebeyi ine matanda matete n...
..         ...                                                ...
887  ID_CUDWBK  munhukadzi akachena. akapfeka hembe ine ruvara...
888  ID_ARVDNP  photo elakisi biso mwa loboko esimbi mwa kisi ...
889  ID_EROPVG  miti yemijakaranda mihombe ine tirangi yakakur...
890  ID_VYRCXO  awa eza esika bakonzi batelemelaka makambo ya ...
891  ID_HYKQPA  chimushini chakatsvetwa pasi paivhu chine ruva...

[892 rows x 2 columns]

In [7]:
submission_lowercased.to_csv("submission_lowercased (8).csv", index=False)

In [9]:
submission_capitalized = submission.copy()
submission_capitalized['Target'] = submission_capitalized['Target'].str.capitalize()
submission_capitalized

            ID                                             Target
0    ID_QNYPTX  Bandeko awa na misu na ngai nazomona obele ban...
1    ID_CLCVQW  Biloko nazomona awa namoni eza obele mama moko...
2    ID_INJFRV  Ishangu mbiri dzemativi ose emakumbo. dzine ru...
3    ID_XKFXQJ  Motuka esali mikolo ebele ezali akufa liboso y...
4    ID_TYVXWN  Miti midiki yakati rebeyi ine matanda matete n...
..         ...                                                ...
887  ID_CUDWBK  Munhukadzi akachena. akapfeka hembe ine ruvara...
888  ID_ARVDNP  Photo elakisi biso mwa loboko esimbi mwa kisi ...
889  ID_EROPVG  Miti yemijakaranda mihombe ine tirangi yakakur...
890  ID_VYRCXO  Awa eza esika bakonzi batelemelaka makambo ya ...
891  ID_HYKQPA  Chimushini chakatsvetwa pasi paivhu chine ruva...

[892 rows x 2 columns]

In [10]:
submission_capitalized.to_csv("submission_capitalized (8).csv", index=False)

In [11]:
submission_without_punctuation = submission.copy()
submission_without_punctuation['Target'] = submission_without_punctuation['Target'].str.replace(r'[^\w\s]', '', regex=True)
submission_without_punctuation

            ID                                             Target
0    ID_QNYPTX  Bandeko awa na misu na ngai nazomona obele ban...
1    ID_CLCVQW  Biloko nazomona awa namoni eza obele mama moko...
2    ID_INJFRV  Ishangu mbiri dzemativi ose emakumbo Dzine ruv...
3    ID_XKFXQJ  Motuka esali mikolo ebele ezali akufa liboso y...
4    ID_TYVXWN  Miti midiki yakati rebeyi ine matanda matete n...
..         ...                                                ...
887  ID_CUDWBK  Munhukadzi akachena Akapfeka hembe ine ruvara ...
888  ID_ARVDNP  Photo elakisi biso mwa loboko esimbi mwa kisi ...
889  ID_EROPVG  Miti yemijakaranda mihombe ine tirangi yakakur...
890  ID_VYRCXO  Awa eza esika bakonzi batelemelaka makambo ya ...
891  ID_HYKQPA  Chimushini chakatsvetwa pasi paivhu Chine ruva...

[892 rows x 2 columns]

In [12]:
submission_without_punctuation.to_csv("submission_without_punctuation (8).csv", index=False)

In [13]:
submission_with_terminal_punctuation = submission.copy()
def add_terminal_punctuation(text):
    if not text.endswith(('.', '!', '?')):
        return text + '.'
    return text

submission_with_terminal_punctuation['Target'] = submission_with_terminal_punctuation['Target'].apply(add_terminal_punctuation)
submission_with_terminal_punctuation

            ID                                             Target
0    ID_QNYPTX  Bandeko awa na misu na ngai nazomona obele ban...
1    ID_CLCVQW  Biloko nazomona awa namoni eza obele mama moko...
2    ID_INJFRV  Ishangu mbiri dzemativi ose emakumbo. Dzine ru...
3    ID_XKFXQJ  Motuka esali mikolo ebele ezali akufa liboso y...
4    ID_TYVXWN  Miti midiki yakati rebeyi ine matanda matete n...
..         ...                                                ...
887  ID_CUDWBK  Munhukadzi akachena. Akapfeka hembe ine ruvara...
888  ID_ARVDNP  Photo elakisi biso mwa loboko esimbi mwa kisi ...
889  ID_EROPVG  Miti yemijakaranda mihombe ine tirangi yakakur...
890  ID_VYRCXO  Awa eza esika bakonzi batelemelaka makambo ya ...
891  ID_HYKQPA  Chimushini chakatsvetwa pasi paivhu Chine ruva...

[892 rows x 2 columns]

In [14]:
submission_with_terminal_punctuation.to_csv("submission_with_terminal_punctuation (8).csv", index=False)

In [15]:
import unicodedata
import re

# text = unicodedata.normalize('NFC', text) # Standardizes composed characters
# text = re.sub(r'\s+', ' ', text).strip()  # Fixes rogue spacing
submission_normalized = submission_with_terminal_punctuation.copy()
submission_normalized['Target'] = submission_normalized['Target'].apply(lambda x: unicodedata.normalize('NFC', x))
submission_normalized['Target'] = submission_normalized['Target'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())
submission_normalized.to_csv("submission_nfc_normalized (8).csv", index=False)

In [16]:
submission_nfkc_normalized = submission_with_terminal_punctuation.copy()
submission_nfkc_normalized['Target'] = submission_nfkc_normalized['Target'].apply(lambda x: unicodedata.normalize('NFKC', x))
submission_nfkc_normalized['Target'] = submission_nfkc_normalized['Target'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())
submission_nfkc_normalized.to_csv("submission_nfkc_normalized (8).csv", index=False)

In [24]:
submission_with_casing_fixed = submission_normalized.copy()

def fix_casing(text):
    """
    Some words have multiple capital letters in the middle of the word, which is not standard. This function fixes that by converting the entire word to lowercase except for the first letter.
    """
    words = text.split()
    for i, word in enumerate(words):
        if word[0].isupper() and len(word) and any(c.isupper() for c in word[1:]):
            print(f"Fixing casing for word: {word}. ", end="")
            words[i] = word[0] + word[1:].lower()
            print(f"Fixed word: {words[i]}")
    return " ".join(words)

submission_with_casing_fixed['Target'] = submission_with_casing_fixed['Target'].apply(fix_casing)
submission_with_casing_fixed.to_csv("submission_with_casing_fixed (8).csv", index=False)

Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: MMusoro. Fixed word: Mmusoro
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: NAwa. Fixed word: Nawa
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: MNhandaro. Fixed word: Mnhandaro
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: BViri. Fixed word: Bviri
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: EAwa. Fixed word: Eawa
Fixing casing for word: EAwa. Fixed word: Eawa